### DISCUSSION TITLE
How to customise link color?

### DISCUSSION THREAD

**Discussion by vorg** [markmap/markmap#163] [Q&A]
It defaults to blue which is hard to read in dark themes. Or I would maybe keep the color and remove underline to improve readability.

![Screenshot 2023-04-09 at 11 28 16](https://user-images.githubusercontent.com/171001/230767584-27a0100e-0af4-46c9-a5d8-8523eddd969a.jpg)

**Comment by gera2ld** [comment]
You can add [custom CSS](https://markmap.js.org/docs/json-options#extracss) to override the existing style.
If you are using it from VSCode, there is a global option called "Custom CSS". (Search options by "markmap")

**Comment by vorg** [comment]
There is such option indeed and i'm able to remove underline

```css
a { text-decoration: none; } /*works!*/
a { color: #FF0000 ;} /*doesn't work*/
a { color: #FF0000 important;} /*doesn't work*/
* { color: #FF0000 ;} /*doesn't work, changes all text beside <a>*/
```

Unfortunately colors for markdown html elements (like links and code blocks) are defined below custom css and i'm not able to overwrite them.

![Screenshot 2023-04-09 at 18 37 16](https://user-images.githubusercontent.com/171001/230787883-88e2c067-32e7-4a7e-b16a-a99b7c6991eb.jpg)

**Comment by vorg** [comment]
This works though  (in Custom CSS setting)

```css
.markmap-foreign a {color:#FF00FF !important; } /*this works*/
```
